apiVersion: apps/v1                 
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: nginx 
    tier: front-end
spec:
  selector:                       
    matchLabels:
      app: myapp
  template:                           
    metadata:
      name: nginx
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3                         
