apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp 
    type: front-end
spec:
  template:                           # specify pod definition under template
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3                         # no. of replicas to be created