apiVersion: v1
kind: Pod
metadata:
  name: results-db
  labels:
    name: db
    type: postgres
spec: 
  containers:
    - name: results-db-container
      image: postgres:9.4
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
