apiVersion: v1
kind: Service
metadata: 
  name: results-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30022
  selector:
    name: results-app
    type: js