apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  labels:
    name: voting-app
    type: python
spec: 
  containers:
    - name: voting-app-container
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
