apiVersion: v1
kind: Service
metadata: 
  name: voting-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30021
  selector:
    name: voting-app
    type: python